### ISSUE TITLE
Retreiving subscriptions

### ISSUE THREAD

**Issue by mickeytgl** [jasoncharnes/pay#10]
How are subscriptions going to be called when trying to retrieve them to update or delete them??

```ruby 
#lib/pay/billable/stripe.rb

      def stripe_subscription(subscription_id)
        ::Stripe::Subscription.retrieve(subscription_id)
      end
```

A possible solution would be to add to the user a `processor_subscription_id` or so so we can call

```ruby 
  ::Stripe::Subscription.retrieve(current_user.processor_subscription_id)
```

But that also means a user can only have one subscription at a time, I believe. Is that OK?

**Comment by excid3** [comment]
Remember, users of this library never _ever_ interact with the Stripe or Braintree directly. They use the methods listed in the readme. 

```ruby
current_user.processor_subscription
```

https://github.com/jasoncharnes/pay#retrieving-a-customers-subscription-from-the-processor

We want to make sure you do this so you don't have to care about the details of Stripe or Braintree. That's what all the methods in Billable.rb are for. When you call them, they figure out how to do what you want in Stripe or Braintree. The developer should never have to know about those details.

**Comment by excid3** [comment]
It's also already setup for multiple subscriptions at once: https://github.com/jasoncharnes/pay/blob/master/lib/pay/billable.rb#L13
