### ISSUE TITLE
Undefined method 'type' when module is included to User

### ISSUE THREAD

**Issue by r-glebov** [jasoncharnes/pay#12]
Hi, 

When I'm trying to include `Pay::Billable` module into `User` and it crashes the app.

```
class User < ActiveRecord::Base
  include Pay::Billable
end
```

I have the following error:

![photoshootings 2017-11-14 21-06-56](https://user-images.githubusercontent.com/8741712/32802413-3d6b86ac-c980-11e7-9cd1-46e56961fe7b.png)

The backtrace:

```
NoMethodError - undefined method `type' for :string:Symbol:
  activerecord (4.2.6) lib/active_record/attribute_methods/time_zone_conversion.rb:64:in `create_time_zone_conversion_attribute?'
  activerecord (4.2.6) lib/active_record/attribute_methods/time_zone_conversion.rb:53:in `block (2 levels) in inherited'
  activerecord (4.2.6) lib/active_record/attribute_decorators.rb:61:in `block in matching'
  activerecord (4.2.6) lib/active_record/attribute_decorators.rb:60:in `matching'
  activerecord (4.2.6) lib/active_record/attribute_decorators.rb:56:in `decorators_for'
  activerecord (4.2.6) lib/active_record/attribute_decorators.rb:47:in `apply'
  activerecord (4.2.6) lib/active_record/attribute_decorators.rb:29:in `block in add_user_provided_columns'
  activerecord (4.2.6) lib/active_record/attribute_decorators.rb:28:in `add_user_provided_columns'
  activerecord (4.2.6) lib/active_record/attributes.rb:93:in `columns'
  activerecord (4.2.6) lib/active_record/attributes.rb:98:in `columns_hash'
  activerecord (4.2.6) lib/active_record/relation/query_methods.rb:969:in `block in create_binds'
```

I use rails 4.2.6.

Have no idea how to fix. Any help would be appreciated :)

By the way, I've noticed another problem with migrations. Generator creates the next migration:

![tomsvideo 2017-11-14 21-14-05](https://user-images.githubusercontent.com/8741712/32802766-846bb184-c981-11e7-94df-fd1a68ce1968.png)

This `[4.2]` crashes the migrations

**Comment by excid3** [comment]
Hey @grBro,

Did you use Devise to create the User model? Right now the views expect that or at least that you have an equivalent `user_signed_in?` method.

What's the error with the migration? I can't remember what version introduced the AR version numbers. I guess it has something to do with that?

**Comment by mani47** [comment]
I'm experiencing the same problem with rails 4.2.4 and devise 3.4.1. And as far as I can tell it's not related to user_signed_in? or views because even if I open rails console and try to get first user this happens:

```
2.3.6 :001 > User.first
  User Load (6.9ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
NoMethodError: undefined method 'type' for :string:Symbol
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_methods/time_zone_conversion.rb:64:in 'create_time_zone_conversion_attribute?'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_methods/time_zone_conversion.rb:53:in 'block (2 levels) in inherited'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_decorators.rb:61:in 'block in matching'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_decorators.rb:60:in 'select'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_decorators.rb:60:in 'matching'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_decorators.rb:56:in 'decorators_for'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_decorators.rb:47:in 'apply'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_decorators.rb:29:in 'block in add_user_provided_columns'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_decorators.rb:28:in 'map'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_decorators.rb:28:in 'add_user_provided_columns'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attributes.rb:93:in 'columns'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attributes.rb:98:in 'columns_hash'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/querying.rb:41:in 'find_by_sql'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/bullet-5.7.1/lib/bullet/active_record42.rb:24:in 'find_by_sql'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/relation.rb:639:in 'exec_queries'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/relation.rb:515:in 'load'
... 8 levels...
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in 'start'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in 'console'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in 'run_command!'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/railties-4.2.4/lib/rails/commands.rb:17:in '<top (required)>'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in 'require'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in 'block in require'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in 'load_dependency'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in 'require'
	from /Users/mani47/Projects/m2m-web/bin/rails:8:in '<top (required)>'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in 'load'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in 'block in load'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in 'load_dependency'
	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in 'load'
	from /Users/mani47/.rvm/rubies/ruby-2.3.6/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in 'require'
	from /Users/mani47/.rvm/rubies/ruby-2.3.6/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in 'require'
	from -e:1:in '<main>'
2.3.6 :002 > 
```

**Comment by redlightmikey** [comment]
> I'm experiencing the same problem with rails 4.2.4 and devise 3.4.1. And as far as I can tell it's not related to user_signed_in? or views because even if I open rails console and try to get first user this happens:
> 
> ```
> 2.3.6 :001 > User.first
>   User Load (6.9ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
> NoMethodError: undefined method 'type' for :string:Symbol
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_methods/time_zone_conversion.rb:64:in 'create_time_zone_conversion_attribute?'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_methods/time_zone_conversion.rb:53:in 'block (2 levels) in inherited'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_decorators.rb:61:in 'block in matching'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_decorators.rb:60:in 'select'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_decorators.rb:60:in 'matching'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_decorators.rb:56:in 'decorators_for'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_decorators.rb:47:in 'apply'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_decorators.rb:29:in 'block in add_user_provided_columns'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_decorators.rb:28:in 'map'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attribute_decorators.rb:28:in 'add_user_provided_columns'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attributes.rb:93:in 'columns'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/attributes.rb:98:in 'columns_hash'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/querying.rb:41:in 'find_by_sql'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/bullet-5.7.1/lib/bullet/active_record42.rb:24:in 'find_by_sql'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/relation.rb:639:in 'exec_queries'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activerecord-4.2.4/lib/active_record/relation.rb:515:in 'load'
> ... 8 levels...
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in 'start'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in 'console'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in 'run_command!'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/railties-4.2.4/lib/rails/commands.rb:17:in '<top (required)>'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in 'require'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in 'block in require'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in 'load_dependency'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in 'require'
> 	from /Users/mani47/Projects/m2m-web/bin/rails:8:in '<top (required)>'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in 'load'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in 'block in load'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in 'load_dependency'
> 	from /Users/mani47/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in 'load'
> 	from /Users/mani47/.rvm/rubies/ruby-2.3.6/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in 'require'
> 	from /Users/mani47/.rvm/rubies/ruby-2.3.6/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in 'require'
> 	from -e:1:in '<main>'
> 2.3.6 :002 > 
> ```

How did this get fixed? I am having the exact same problem....
