### ISSUE TITLE
Safe for production use?

### ISSUE THREAD

**Issue by saulcosta** [jasoncharnes/pay#47]
Hello!

This gem looks really promising but currently does not have a stable release, although it appears to be getting close to one. Would you recommend avoiding use in a production environment at this time? Are there any considerations we should take into account if we do right now?

Thanks!

**Comment by excid3** [comment]
@saulcosta Not just yet, we're really close to a 1.0 release but still ironing out a few bugs and getting our test suite more robust. Should be ready before the end of January though. 👍

**Comment by saulcosta** [comment]
Thanks for the fast response. Do you know if there be breaking changes between the current `master` and `1.0` release?

**Comment by excid3** [comment]
Probably nothing major at this point. We're just fixing any issues that come up in testing, so I think the methods and arguments are generally all good. 

We may have a couple argument changes here or there at most I would imagine if we discover something we overlooked.

**Comment by saulcosta** [comment]
Okay great, thanks for the info. I'll close this. Looking forward to the stable release!
