### ISSUE TITLE
Send email to all team admins upon subscribe.

### ISSUE THREAD

**Issue by deep0389** [jasoncharnes/pay#49]
Currently, the subscribe method is looking for an email attribute on the `Pay.billable_table`table.
However, in my case, I have a team with multiple users in it and there is no email in the team table.

- I also tried running `rails generate pay:email_views`. It says "Could not find generator 'pay:email_views'."
- I also tried using `config.send_emails = false` in the initializer. I get error "undefined method `send_emails=' for Pay:Module (NoMethodError)"
Looks like the code is there in the master but not released to RubyGems.

How do I handle this use case?

**Comment by excid3** [comment]
@deep0389 what you should do then is just add an email method that delegates to the proper email address.

```ruby
class Team
  include Pay::Billable
 
  belongs_to :owner

  def email
    # This just needs to return an email address so you can put any logic you want here to retrieve it
    owner.email
  end

  # or using the Rails helper which will call the email method on the owner
  # delegate :email, to: :owner
end
```

**Comment by deep0389** [comment]
I was able to overcome this issue with the suggested code. However, I am running into lots of other errors, probably because email field is not there in Team table.
The following methods are also undefined as I move forward.

saved_change_to_email
sync_email_with_processor

wondering if I should choose some other gem for production use right now

**Comment by excid3** [comment]
@deep0389 I just pushed up a change (ffa841f) to only sync email changes with processor if they respond to that.
