### ISSUE TITLE
How to use the gem to have a user linked to multiple items each with one subscription?

### ISSUE THREAD

**Issue by jean-francois-labbe** [jasoncharnes/pay#59]
Hi,

I don't know how to use this gem to support the following idea: I want a user to have a subscription per item.

I have the current prototype, that allows one item to be billable.

```ruby
class Item < ApplicationRecord
  include Pay::Billable
  belongs_to :use
  ...
end

class User < ApplicationRecord
  has_many :items
  ... 
end
```

With this prototype, the subscription can be created.

But if the user creates a new item and a subscription for it, In Stripe a new customer(user) is created

I don't want one cutomer per Item, I want one customer per User.

How should I structure my code to make it work?
```ruby
class Item < ApplicationRecord
  belongs_to :use
  ...
end

class User < ApplicationRecord
  include Pay::Billable
  has_many :items
  ...
end
```
I suppose this will make my user unique, but how do I link the item to the subscription?

**Comment by excid3** [comment]
Let's take a step back. What are you trying to do? Allow users to have a subscription per item?

**Comment by jean-francois-labbe** [comment]
Exactly

**Comment by excid3** [comment]
Okay awesome. Then in that case, I think you'll simply want to use the name argument to `subscribe`. That allows for you to have one customer with multiple subscriptions. Each one just needs a unique name.

https://github.com/jasoncharnes/pay#creating-a-subscription

**Comment by jean-francois-labbe** [comment]
That could work, storing the item `id`  (something that won't change and is unique) into the subscription name, but I find it odd, it's not name purpose to store the item id.

I would have liked to get the `Item#subscribed?` method.

I think it could be useful to have the option to link a subscription to something (ie: Item in my case)

I will try to store the subscription id into the item to have a direct relation.

**Comment by excid3** [comment]
Well, the main thing is that subscriptions are for a customer in all payment processors. We want to model that primarily.

It just so happens that you also want to associate that subscription to a record in your db.

You can just as easily add a migration to add Item ID to the subscription model and extend pay.

```ruby
class Item
  has_one :subscription

  def subscribe
    sub = user.subscribe(id)
    sub.update(item_id: id)
  end
end
```

Then you should be able to simply reopen the subscription model and add your belongs_to:

```ruby
module Pay
  class Subscription < ApplicationRecord
    belongs_to :item
  end
end
```

**Comment by jean-francois-labbe** [comment]
Thanks it works :+1: 

I used: `has_one :subscription, -> {where(ends_at: nil)}, class_name: "Pay::Subscription" `

If I put 
```ruby
module Pay
  class Subscription < ApplicationRecord
    belongs_to :item
  end
end
```
into `app/models/subscription.rb` I get the following error: `undefined method `advert' for #<Pay::Subscription:0x00005626a635f318>` even after restarting the server

So I created a new file: `config/initializers/subscription.rb` 

```ruby
require "pay/stripe"

# Patch pay subscription to link it to an Item
# Users pay per Item, so we need to be able to easily link it to a subscription
Pay::Subscription.class_eval do
  include Pay::Stripe::Subscription
  belongs_to :item, required: false
end
```

It works. But I have some issues with rails reloading, I often got an issue where it cannot find `subscription.item`. I just restart Rails server and it's ok.

Do you have any idea why?

**Comment by excid3** [comment]
Is `advert` a column you added or something? Doesn't sound like anything we have in the gem.

You defined Pay::Subscription in `models/subscription` but that should probably be `models/pay/subscription` to properly follow the Rails autoloader rules. 

Try that and see if it fixes it?

**Comment by jean-francois-labbe** [comment]
Oh sorry, in my case `advert` is an `item`, I'll edit the previous comment

**Comment by jean-francois-labbe** [comment]
I tried to put it in: `app/models/pay/subscription.rb`

I had to add `self.table_name = Pay.subscription_table`

but now I get the following error: 
```ruby
current_user.subscriptions
=> Could not find the inverse association for subscriptions (:owner in Pay::Subscription)
```

**Comment by jean-francois-labbe** [comment]
I had to add `belongs_to :owner, class_name: Pay.billable_class, foreign_key: :owner_id` to make it work.
I don't understand why I loosing `belongs_to` and `self.table_name` that are already declared in your gem

The final file is:
```ruby
require "pay/stripe"

module Pay
  class Subscription < ApplicationRecord
    self.table_name = Pay.subscription_table
    belongs_to :owner, class_name: Pay.billable_class, foreign_key: :owner_id

    include Pay::Stripe::Subscription
    belongs_to :item, required: false
  end
end


```

**Comment by jean-francois-labbe** [comment]
But it's not really working cause now I got `undefined method active?' for #Pay::Subscription:0x0000564a3ddf0fb0>` And I also miss all the methods you defined in your gem

**Comment by excid3** [comment]
Gotcha regarding `advert`. I was like where did this come from? :)

Let me spin up a test app to see about reopening the subscription class. I'll let you know what I find.

**Comment by jean-francois-labbe** [comment]
I got an error at rails server start: `config/initializers/subscription_extensions.rb:4:in `<module:SubscriptionExtensions>': undefined method `belongs_to' for SubscriptionExtensions:Module (NoMethodError)`

**Comment by excid3** [comment]
Sorry that should be:

```ruby
# config/initializers/subscription_extensions.rb
module SubscriptionExtensions
  extend ActiveSupport::Concern

  included do
    belongs_to :item
  end
end

Pay::Subscription.include SubscriptionExtensions
```

**Comment by jean-francois-labbe** [comment]
Awesome :+1: Thanks a lot.

**Comment by jean-francois-labbe** [comment]
What do you think if I add a bit of documentation about this use case?

**Comment by excid3** [comment]
I'd appreciate that! 

I'm going to try and look into how we can make it easier to re-open the class in your models directory, but for now this should be fine.

**Comment by jean-francois-labbe** [comment]
Thanks @excid3 the `SubscriptionExtensions` works. But I then have the reload error that you mention here: https://github.com/jasoncharnes/pay/issues/69#issuecomment-462369878

**Comment by jean-francois-labbe** [comment]
I think I have an issue with rails reloader now.
Since I modify povided `Pay::Subscription` as describe here: https://github.com/jasoncharnes/pay/issues/59#issuecomment-461641739 I think when the class is reloaded the `Pay::Subscription.include SubscriptionExtensions` disapears.

**Comment by excid3** [comment]
You may still have this issue with the reload in development, so you'll need to wrap your include in the Rails reloader.

```ruby
Rails.application.config.to_prepare do
  Pay::Subscription.include SubscriptionExtensions
end
```

This way if the Pay::Subscription model ever gets reloaded, you'll also re-include your changes.

**Comment by jean-francois-labbe** [comment]
Seems to be working at first sight, I'll check that in depth later.
It's kind of hard to find documentation on the topic.
Thanks a lot.

**Comment by excid3** [comment]
Yeah, that's why it took me so long to figure out the solution. :)

The way to test it is to open a console and run:

```
Pay::Subscription.included_modules
reload!
Pay::Subscription.included_modules
```

You should see your SubscriptionExtensions module in there both times.

**Comment by jean-francois-labbe** [comment]
It's working :tada:

**Comment by excid3** [comment]
Awesome! That's great news. 🤘
