### ISSUE TITLE
Card Token Is Not Getting Passed 

### ISSUE THREAD

**Issue by grichardomi** [jasoncharnes/pay#63]
I followed instructions here: https://github.com/jasoncharnes/pay/wiki/Using-Stripe-Elements-and-Devise

STRIPE_SIGNING_SECRET is set 

However, customer card_token is not getting injected to form.

Any suggestions?

**Comment by excid3** [comment]
First, STRIPE_SIGNING_SECRET is for webhooks, not the form just so you're aware.

The Stripe Public Key is what the form needs to generate a card_token. Make sure you replaced the string here with your public key.

```js
  var stripe = Stripe('your public stripe key');
```

You can also console.log the token handler to see when it's being run. I also like to comment out the `form.submit()` here so it's easier to test. Uncomment it when you get everything working and see the token print out in the JS console.

```js
  function stripeTokenHandler(token) {
    // Insert the token ID into the form so it gets submitted to the server
    var form = document.getElementById('payment-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'user[card_token]');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);

    console.log(token)

    // Submit the form
    //form.submit();
  }
```

**Comment by grichardomi** [comment]
I'm seeing nothing in my console log. My setup may not be correct. 

Stripe Js correctly populated form with credit card fields.

The following was pasted to my devise user_registration,  new.html.erb:
 
 <script src="https://js.stripe.com/v3/"></script>
<script>
  var stripe = Stripe('pk_test_TmQg6vPbB7PdTXshZaPffiK8');
  var elements = stripe.elements();

  // Create an instance of the card Element
  var card = elements.create('card');
  card.mount('#card-element');

  // Listen for Card Errors
  card.addEventListener('change', function(event) {
    var displayError = document.getElementById('card-errors');
    if (event.error) {
      displayError.textContent = event.error.message;
    } else {
      displayError.textContent = '';
    }
  });
</script>

<script>
  var form = document.getElementById('new_user');
  form.addEventListener('submit', function(event) {
    event.preventDefault();

    stripe.createToken(card).then(function(result) {
      if (result.error) {
        // Inform the user if there was an error
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
      } else {
        // Send the token to your server
        stripeTokenHandler(result.token);
      }
    });
  });
</script>


<script>
  function stripeTokenHandler(token) {
    // Insert the token ID into the form so it gets submitted to the server
    var form = document.getElementById('payment-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'user[card_token]');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);

    console.log(token)

    // Submit the form
    // form.submit();
  }
</script> 

What could be missing?

**Comment by grichardomi** [comment]
Related console error message:  Uncaught TypeError: Cannot read property 'addEventListener' of null

**Comment by grichardomi** [comment]
Changed "user" below to new billable_class to no avail

 hiddenInput.setAttribute('name', '**user**[card_token]');

**Comment by eelcoj** [comment]
Is `<script src="https://js.stripe.com/v3/"></script>` into the head? Are the other JS loaded after dom is ready/Turbolinks is loaded?

**Comment by grichardomi** [comment]
I really appreciate all the help.

Using debugger, cannot see token in params variables.

Tried tagging form id with "payment-form" to no avail:
var form = document.getElementById('**payment-form**');

**Comment by grichardomi** [comment]
Got it working. Needed to replace "payment-form" with billable-class.

Thanks to all.

**Comment by excid3** [comment]
@grichardomi glad you got it working! Yeah, having the matching ID lookup is important. We can update the wiki to make sure that's more obvious. 👍

**Comment by grichardomi** [comment]
Great work!
