### ISSUE TITLE
Dealing With Duplicated Customers

### ISSUE THREAD

**Issue by grichardomi** [jasoncharnes/pay#64]
My failed form token retries created lot of duplicated customers in Stripe. 

Is there a convenient way to prevent duplicates if user.subscribe failed? Another way would be to test for duplicates in Stripe using email?

**Comment by excid3** [comment]
This is one of the hard parts about getting a credit card when signing up. You'll need to delete the Stripe customer if it fails.

To do that, you'll have to override the Devise::RegistrationsController and replace part of the create action.

```ruby
class RegistrationsController < Devise::RegistrationsController
  def create
    super do
        if resource.persisted?
          begin
            resource.subscribe
          rescue Pay::Error => e
            resource.customer.delete
            flash[:alert] = e.message
          end
        end
    end
  end
end
```

Note: this would only work for Stripe, to delete a braintree customer it's a little different. We may need to build a method to delete the customer into Pay so it's generic.

**Comment by grichardomi** [comment]
That makes sense. Awesome. Thanks!
