### ISSUE TITLE
Coupon Option?

### ISSUE THREAD

**Issue by grichardomi** [jasoncharnes/pay#65]
Noticed that coupon cannot be applied to subscription upon creation. Is it on the things to do list?

**Comment by excid3** [comment]
Whoops, yeah we need to modify that to pass along extra options to Stripe. Give me a minute to fix that.

**Comment by excid3** [comment]
The following should work now:

```ruby
user.subscribe(
  name: 'default', 
  plan: 'plan_id', 
  coupon: 'free-period'
)
```

**Comment by grichardomi** [comment]
I thank you for making life less stressful!
