### ISSUE TITLE
Access Subscription Charges

### ISSUE THREAD

**Issue by grichardomi** [jasoncharnes/pay#68]
Noticed that subscription charges are not posted to pay_charges table.

Is there a way to access subscription related charges, to also include coupons?

**Comment by excid3** [comment]
They are added to the table view webhooks.

There's currently no association between a charge a subscription, but something we may add soon.

**Comment by grichardomi** [comment]
Ok, thanks!

**Comment by grichardomi** [comment]
Association between a charge and subscription may not be needed since webhooks update charges.

Meantime, pay_subscriptions are recorded. But pay_charges are not getting created when a subscription succeeds.

**Comment by excid3** [comment]
Pay::Charges only get created by webhooks, so you'll want to make sure you have one setup and pointed to your development machine. I would recommend using localtunnel or ngrok.

**Comment by grichardomi** [comment]
I used this as my webhooks endpoint: **https://website.com/webhooks/stripe**

And it seems to work fine.

However, Stripe support informed that "The failing webhook endpoint is **https://website.com/webhooks/stripe**. You or someone on your team has added that endpoint in your Stripe webhook settings, which you can view and edit here: https://dashboard.stripe.com/account/webhooks.
"

Is "https://website.com/webhooks/stripe" as valid endpoint format?

**Comment by excid3** [comment]
Have you checked your Rails logs to see what's failing?

**Comment by grichardomi** [comment]
No route matches [GET] "/webhooks/stripe"

**Comment by excid3** [comment]
Hmm, not sure about that. The routes are definitely there in the gem.

https://github.com/jasoncharnes/pay/blob/master/config/routes.rb#L1

You should see them in `rails routes`

**Comment by grichardomi** [comment]
Yes.  It is failing without the event.

**webhooks_stripe_path | POST | /webhooks/stripe(.:format) | stripe_event/webhook#event**

Testing webhooks as Stripe support outlined will always fail without the event.  

Do we need to add webhooks for all the events? If so, any example?

**Comment by grichardomi** [comment]
Failing is on Get request.

**Comment by excid3** [comment]
Ah are you just sending a test webhook, not a real one?

**Comment by excid3** [comment]
Webhooks are only POST, not GET, so that's why your route is missing.

**Comment by grichardomi** [comment]
Webhooks work in real-time.

However, Stripe support expects this to not return a routing error:  "https://website.com/webhooks/stripe" 

Is that possible? or do we need to add endpoints with event in webhooks setting?

**Comment by excid3** [comment]
You would add the url to your webhook settings in Stripe.

>Webhook data is sent as JSON in the POST request body. The full event details are included and can be used directly, after parsing the JSON into an Event object.

**Comment by grichardomi** [comment]
I thank that Stripe was trying to validate a live endpoint that was incorrectly listed in a test environment.
Thanks @excid3!

**Comment by excid3** [comment]
Ah! That would do it. 👍
