### ISSUE TITLE
undefined method `create_stripe_subscription' for User.

### ISSUE THREAD

**Issue by jean-francois-labbe** [jasoncharnes/pay#69]
Hi,
I'm facing this issue **undefined method `create_stripe_subscription' for #<User:0x0000557d8d2a3518> Did you mean? create_subscription**

It works few times then it crash. Do you have any idea why?

Pay version: 1.0.0.alpha1, master@0c93698

**Comment by jasoncharnes** [comment]
I’ll take a look.

**Comment by jasoncharnes** [comment]
To better understand, does this error raise when calling `subscribe` on your `User` model? Or are you calling `create_stripe_subscription`?

**Comment by excid3** [comment]
It has to do with the ActiveSupport reloader. I've been having trouble with it reloading the model and then not re-injecting the concerns.

**Comment by jean-francois-labbe** [comment]
here is what I do.

In an Item class:

```ruby
class Item
  has_one :subscription, -> {where(ends_at: nil)}, class_name: "Pay::Subscription"

  def subscribe
    subscription = user.subscribe(name: subscription_key, plan: "plan_id")
    subscription.update(item_id: id)
  end
end
```

```ruby
class User < ApplicationRecord
  include Pay::Billable
  has_many :items
end
```

**Comment by excid3** [comment]
I think I have a fix for this. It's been bugging me for a few weeks but I couldn't figure it out until this morning.

Will let you know when it's ready to try.

**Comment by jean-francois-labbe** [comment]
Awesome :+1:

**Comment by excid3** [comment]
Try updating to alpha3 now. I think we should be fixed.

**Comment by jean-francois-labbe** [comment]
This is fixed for me.

**Comment by excid3** [comment]
WHOO!! That's been bugging me for a few weeks now. Really glad to have that fixed. 🙌

**Comment by jean-francois-labbe** [comment]
Yeah :fireworks:  , but I still have one Reload issue on my side due to the modification of Pay::Subscription class in my application

**Comment by excid3** [comment]
Did you see my comment in that thread?

**Comment by jean-francois-labbe** [comment]
Yes, I applied the change, Thanks a lot
