### ISSUE TITLE
Error in solidus

### ISSUE THREAD

**Issue by sechix** [jasoncharnes/pay#7]
I trying to add this extension to solidus (fork of spree commerce) but Give me error:

I add this:
module Spree
  class User < Spree::Base
    include Pay::Billable
    end
end

But if I use:
	<% user = Spree::User.find_by(email: @user.email)%>
<%@user_subscriptions = Spree::User.subscription %>

Give this error:
undefined method `subscription' for #<Class:0x007f922674b200>

**Comment by jasoncharnes** [comment]
@sechix so sorry I'm just now circling back to this. I had emailed notifications turned off, for some odd reason. I'm very sorry!

If you are still interested in the answer (once again, sorry about that!) 

The code you included

```erb
<% user = Spree::User.find_by(email: @user.email) %>
<% @user_subscriptions = Spree::User.subscription %>
```

is trying to call `subscription` on a `Spree::User` class, versus a `Spree::User` instance.

You'd want to try:

```erb
<% user = Spree::User.find_by(email: @user.email) %>
<% @user_subscriptions = user.subscription %>
```

**Comment by sechix** [comment]
Thanks jason, finally i solved this!!!
