### ISSUE TITLE
How to customize webhooks user notifications

### ISSUE THREAD

**Issue by jean-francois-labbe** [jasoncharnes/pay#72]
Hello,

Your gem can send emails to user upon some [webhooks](https://github.com/jasoncharnes/pay/blob/master/lib/pay/stripe/webhooks/charge_succeeded.rb), is there any way to customize/hook into the user notification?

Use case could be to create a notification in the webapp and/or a push notification on mobile.

**Comment by excid3** [comment]
To modify the webhooks, you just need to override the call method on them.

```ruby
module Pay
  module Stripe
    module Webhooks

      class ChargeRefunded
        def call(event)
           # custom handling
        end
      end
    end
  end
end
```

**Comment by excid3** [comment]
I think long-term we can make a Pay::Webhooks module that each processor can use to pass in their data so that we don't have duplication between the processors.

**Comment by jean-francois-labbe** [comment]
Right, that way I can just redefine `notify_user`

**Comment by mryurii** [comment]
Hint - you need to ensure that overridden class properly loaded in the application 😑
